name: "Run Unit Tests"
on:
  push:
    branches:
      - "merge-updates"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: "Install Python 3"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.6
      - name: "Setup Virtual Environment"
        run: |
          python -m venv .venv
          . ./.venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          site_packages=$(python -m site --user-site)
          bfproto_dir=$(realpath ./proto)
          python -m grpc_tools.protoc \
            --proto_path=${bfproto_dir} \
            --proto_path=${site_packages} \
            --python_out=${site_packages} \
            --grpc_python_out=${site_packages} \
                ${bfproto_dir}/bfruntime.proto
      - name: "Run Tests"
        run:
          . ./.venv/bin/activate
          python -m pytest
          
      