name: "Run Unit Tests"
on:
  push:
    branches:
      - "merge-updates"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: "Install Python 3"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.6
      - name: "Clone Google Common Protos"
        uses: "actions/checkout@v2"
        with:
          repository: "googleapis/api-common-protos"
      - name: "Setup Virtual Environment"
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
          mkdir -p gen-py
          ls -lrth $GITHUB_WORKSPACE
          python -m grpc_tools.protoc \
            --proto_path=${bfproto_dir} \
            --proto_path=./api-common-protos \
            --python_out=./gen-py \
            --grpc_python_out=./gen-py \
                $GITHUB_WORKSPACE/proto/bfruntime.proto
      - name: "Run Tests"
        env:
          PYTHONPATH: $GITHUB_WORKSPACE/gen-py
        run:
          python -m pytest -v
          
      