name: "Run Unit Tests"
on:
  push:
    branches:
      - "merge-updates"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: "Install Python 3"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.6
      - name: "Cache BfRuntime Protobuf"
        id: "cache-bfrt-protobuf"
        uses: "actions/cache@v2"
        with:
           path: "gen-py"
           key: ${{ runner.os }}-bfrt-protobuf

      - uses: "syphar/restore-virtualenv@v1"
        id: "cache-virtualenv"
      - name: "Setup Virtual Environment"
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: "Install Bfrt Helper"
        run: "pip install -e ."
      - name: "Clone Google Common Protos"
        if: steps.cache-bfrt-protobuf.outputs.cache-hit != 'true'
        uses: "actions/checkout@v2"
        with:
          repository: "googleapis/api-common-protos"
          path: "api-common-protos"
          clean: false
      - name: "Generate BfRuntime Protobuf"
        if: steps.cache-bfrt-protobuf.outputs.cache-hit != 'true'
        run: |
          mkdir -p gen-py
          python -m grpc_tools.protoc \
            --proto_path=${{ github.workspace }}/proto \
            --proto_path=${{ github.workspace }}/api-common-protos \
            --python_out=${{ github.workspace }}/gen-py \
            --grpc_python_out=./gen-py \
                ${{ github.workspace }}/proto/bfruntime.proto

      - name: "Run Tests"
        env:
          PYTHONPATH: ${{ github.workspace }}/gen-py
        run:
          python -m pytest -v --cov=bfrt_helper --cov-report html

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: "Install Python 3"
        uses: "actions/setup-python@v2"
      - name: "Install Linters"
        run: "pip install flake8 black"
      - name: "Run linters"
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true