name: "Run Unit Tests"
on:
  push:
    branches:
      - "develop"
  pull_request:
    branches: 
      - "develop"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Install Python 3"
        uses: "actions/setup-python@v2"

      - uses: "syphar/restore-virtualenv@v1"
        id: "cache-virtualenv"

      - name: "Setup Virtual Environment"
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip

      - name: "Install Bfrt Helper"
        run: |
          pip install -e .

      - name: "Run Tests"
        env:
          PYTHONPATH: ${{ github.workspace }}/gen-py
        run:
          python -m pytest -v --cov=bfrt_helper --cov-report html
      - name: "Save Coverage Report"
        uses: actions/upload-artifact@v2
        with:
          name: "coverage-report"
          path: "htmlcov"


  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Install Python 3"
        uses: "actions/setup-python@v2"

      - name: "Install Linters"
        run: "pip install flake8 black"
      # - uses: "syphar/restore-virtualenv@v1"
      #   id: "cache-virtualenv"


      # - name: "Setup Virtual Environment"
      #   if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: "Run linters"
        uses: "wearerequired/lint-action@v1"
        with:
          black: false
          flake8: true
          flake8_args: "--max-line-length=100 --exclude bfrt_helper/pb2"